[target.aarch64-unknown-linux-gnu]
image = "clux/muslrust:stable"
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get -y install libssl-dev"
]

[target.x86_64-unknown-linux-musl]
image = "clux/muslrust:stable"
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get -y install libssl-dev"
]
env.passthrough = [
    "CC=musl-gcc",
    "CXX=g++",
]
