name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare
      run: |
        rustup target add aarch64-unknown-linux-musl x86_64-unknown-linux-musl
        cargo install cross

    - name: Build linux-amd64
      run: cross build -v --release --target x86_64-unknown-linux-musl

#    - name: Build linux-arm64
#      run: cross build --package tui -v --release --target aarch64-unknown-linux-gnu

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          target/**/tui